services:
  postgres:
    image: postgres:16-alpine
    container_name: timewin_db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: timewin
      POSTGRES_PASSWORD: timewin_secret
      POSTGRES_DB: timewin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
